"""add cardinality and parent to field

Revision ID: 438c0ee9f326
Revises: 01fb7b23bc27
Create Date: 2025-01-23 08:58:45.265566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438c0ee9f326'
down_revision = '01fb7b23bc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardinality', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_field', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field', schema=None) as batch_op:
        batch_op.drop_column('parent_field')
        batch_op.drop_column('cardinality')

    # ### end Alembic commands ###
