"""move org/orgs out of Record.data to field on record. Modify organisation

Revision ID: aed9a5a15c2d
Revises: 867739846102
Create Date: 2025-01-28 14:56:09.538734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aed9a5a15c2d'
down_revision = '867739846102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation', sa.Text(), nullable=False))
        batch_op.drop_constraint('organisation_pk', type_='primary')
        batch_op.create_primary_key('organisation_pk', ['organisation'])
        batch_op.drop_column('reference')
        batch_op.drop_column('prefix')

    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('organisation_ids', postgresql.ARRAY(sa.Text()), nullable=True))
        batch_op.create_foreign_key("organisation_record_fk", 'organisation', ['organisation_id'], ['organisation'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_constraint('organisation_record_fk', type_='foreignkey')
        batch_op.drop_column('organisation_ids')
        batch_op.drop_column('organisation_id')

    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('organisation_pk', type_='primary')
        batch_op.drop_column('organisation')
        batch_op.create_primary_key('organisation_pk', ['prefix', 'reference'])

    # ### end Alembic commands ###
